// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentana.API.Models;

#nullable disable

namespace Sentana.API.Migrations
{
    [DbContext(typeof(SentanaContext))]
    [Migration("20260402042844_InitialCreate_Fresh")]
    partial class InitialCreate_Fresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sentana.API.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TechAvailability")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA5A6E24D5BAA");

                    b.HasIndex("InfoId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UC_Account_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "UserName" }, "UC_Account_UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("ApartmentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ApartmentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<double?>("Area")
                        .HasColumnType("float");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("StartDay")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ApartmentId")
                        .HasName("PK__Apartmen__CBDF57643BC9C0CD");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartment", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.ApartmentResident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("RelationshipId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ResidentId")
                        .HasName("PK__Apartmen__07FB00DC876178DD");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("Apartment_Resident", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.ApartmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDay")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDay")
                        .HasColumnType("date");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__Apartmen__3214EC07F793566A");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Apartment_Service", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("BuildingId")
                        .HasName("PK__Building__5463CDC426E62496");

                    b.HasIndex("ManagerId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdditionalCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("EndDay")
                        .HasColumnType("date");

                    b.Property<string>("File")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MonthlyRent")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Monthly_rent");

                    b.Property<decimal?>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateOnly?>("StartDay")
                        .HasColumnType("date");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ContractId")
                        .HasName("PK__Contract__C90D34697BEDBA24");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CurrentVersionId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.ContractVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VersionNumber")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("VersionId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractVersions");
                });

            modelBuilder.Entity("Sentana.API.Models.ElectricMeter", b =>
                {
                    b.Property<int>("ElectricMeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectricMeterId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("NewIndex")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OldIndex")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ElectricMeterId")
                        .HasName("PK__Electric__5965F9825D9FD95F");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ElectricMeter", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<byte?>("Action")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Screen")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("HistoryId")
                        .HasName("PK__History__4D7B4ABDEEC563FB");

                    b.HasIndex("AccountId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.InFo", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CmndCccd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CMND_CCCD");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte?>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InfoId")
                        .HasName("PK__InFo__4DEC9D7AFAE5911D");

                    b.HasIndex(new[] { "CmndCccd" }, "UC_IdentityCard")
                        .IsUnique()
                        .HasFilter("[CMND_CCCD] IS NOT NULL");

                    b.ToTable("InFo", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BillingMonth")
                        .HasColumnType("int");

                    b.Property<int?>("BillingYear")
                        .HasColumnType("int");

                    b.Property<string>("CodeVoucher")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DayCreat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DayPay")
                        .HasColumnType("date");

                    b.Property<decimal?>("Debt")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ElectricMeterId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ElectricNumber")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManagerNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte?>("Payments")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("WaterMeterId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaterNumber")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoice__D796AAB55697E9EC");

                    b.HasIndex("ContractId");

                    b.HasIndex("ElectricMeterId");

                    b.HasIndex("WaterMeterId");

                    b.HasIndex("ApartmentId", "BillingMonth", "BillingYear")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.IssueCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("DefaultPriority")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("CategoryId")
                        .HasName("PK__IssueCat__19093A0BB4D2774C");

                    b.ToTable("IssueCategory", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FixDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte?>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RequestId")
                        .HasName("PK__Maintena__33A8517A188C33C5");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CategoryId");

                    b.ToTable("MaintenanceRequest", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<DateOnly?>("CreateDay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NewsId")
                        .HasName("PK__News__954EBDF3375578DC");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Sentana.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccountId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Sentana.API.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentProofImage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TransactionId")
                        .HasName("PK__PaymentT__55433A6BB4E4FF75");

                    b.HasIndex("InvoiceId");

                    b.ToTable("PaymentTransaction", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Relationship", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RelationshipName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RelationshipId")
                        .HasName("PK__Relation__31FEB881A6A95BFC");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Sentana.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A75A93101");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB00A8A0FFE94");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.WaterMeter", b =>
                {
                    b.Property<int>("WaterMeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaterMeterId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("NewIndex")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OldIndex")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("WaterMeterId")
                        .HasName("PK__WaterMet__28A46589141413EA");

                    b.HasIndex("ApartmentId");

                    b.ToTable("WaterMeter", (string)null);
                });

            modelBuilder.Entity("Sentana.API.Models.Account", b =>
                {
                    b.HasOne("Sentana.API.Models.InFo", "Info")
                        .WithMany("Accounts")
                        .HasForeignKey("InfoId")
                        .HasConstraintName("FK_Account_InFo");

                    b.HasOne("Sentana.API.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Info");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sentana.API.Models.Apartment", b =>
                {
                    b.HasOne("Sentana.API.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK_Apartment_Building");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Sentana.API.Models.ApartmentResident", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Account")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_AptRes_Account");

                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_AptRes_Apartment");

                    b.HasOne("Sentana.API.Models.Relationship", "Relationship")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("RelationshipId")
                        .HasConstraintName("FK_AptRes_Relationship");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Sentana.API.Models.ApartmentService", b =>
                {
                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("ApartmentServices")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_AptSvc_Apartment");

                    b.HasOne("Sentana.API.Models.Service", "Service")
                        .WithMany("ApartmentServices")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_AptSvc_Service");

                    b.Navigation("Apartment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Sentana.API.Models.Building", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Sentana.API.Models.Contract", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Account")
                        .WithMany("Contracts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Contract_Account");

                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("Contracts")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_Contract_Apartment");

                    b.HasOne("Sentana.API.Models.ContractVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Sentana.API.Models.ContractVersion", b =>
                {
                    b.HasOne("Sentana.API.Models.Contract", "Contract")
                        .WithMany("ContractVersions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Sentana.API.Models.ElectricMeter", b =>
                {
                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("ElectricMeters")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_ElecMeter_Apartment");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Sentana.API.Models.History", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Account")
                        .WithMany("Histories")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_History_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Sentana.API.Models.Invoice", b =>
                {
                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("Invoices")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_Invoice_Apartment");

                    b.HasOne("Sentana.API.Models.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_Invoice_Contract");

                    b.HasOne("Sentana.API.Models.ElectricMeter", "ElectricMeter")
                        .WithMany("Invoices")
                        .HasForeignKey("ElectricMeterId")
                        .HasConstraintName("FK_Invoice_Electric");

                    b.HasOne("Sentana.API.Models.WaterMeter", "WaterMeter")
                        .WithMany("Invoices")
                        .HasForeignKey("WaterMeterId")
                        .HasConstraintName("FK_Invoice_Water");

                    b.Navigation("Apartment");

                    b.Navigation("Contract");

                    b.Navigation("ElectricMeter");

                    b.Navigation("WaterMeter");
                });

            modelBuilder.Entity("Sentana.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Account")
                        .WithMany("MaintenanceRequestAccounts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_MaintReq_Account");

                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_MaintReq_Apartment");

                    b.HasOne("Sentana.API.Models.Account", "AssignedToNavigation")
                        .WithMany("MaintenanceRequestAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK_MaintReq_AssignedTo");

                    b.HasOne("Sentana.API.Models.IssueCategory", "Category")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_MaintReq_Category");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sentana.API.Models.Notification", b =>
                {
                    b.HasOne("Sentana.API.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Sentana.API.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Sentana.API.Models.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK_PayTrans_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Sentana.API.Models.WaterMeter", b =>
                {
                    b.HasOne("Sentana.API.Models.Apartment", "Apartment")
                        .WithMany("WaterMeters")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_WaterMeter_Apartment");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Sentana.API.Models.Account", b =>
                {
                    b.Navigation("ApartmentResidents");

                    b.Navigation("Contracts");

                    b.Navigation("Histories");

                    b.Navigation("MaintenanceRequestAccounts");

                    b.Navigation("MaintenanceRequestAssignedToNavigations");
                });

            modelBuilder.Entity("Sentana.API.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentResidents");

                    b.Navigation("ApartmentServices");

                    b.Navigation("Contracts");

                    b.Navigation("ElectricMeters");

                    b.Navigation("Invoices");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("WaterMeters");
                });

            modelBuilder.Entity("Sentana.API.Models.Building", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("Sentana.API.Models.Contract", b =>
                {
                    b.Navigation("ContractVersions");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Sentana.API.Models.ElectricMeter", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Sentana.API.Models.InFo", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Sentana.API.Models.Invoice", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Sentana.API.Models.IssueCategory", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("Sentana.API.Models.Relationship", b =>
                {
                    b.Navigation("ApartmentResidents");
                });

            modelBuilder.Entity("Sentana.API.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Sentana.API.Models.Service", b =>
                {
                    b.Navigation("ApartmentServices");
                });

            modelBuilder.Entity("Sentana.API.Models.WaterMeter", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
